[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "trading_client"
version = "0.1.0"
description = "Trading Client"
dependencies = ["textual", "rich", "httpx", "textual-plotext", "humanize"]
requires-python = ">=3.10"
readme = "README.md"
